baseURL = 'https://LakshyaRastogi25.github.io/'
languageCode = 'en-us'
title = 'Lakshya Rastogi'
theme = 'PaperMod'

[params]
  author = "Lakshya Rastogi"
  defaultTheme = "dark"
  mainSections = ["posts"]
  ShowReadingTime = true
  ShowCodeCopyButtons = true

    [params.profileMode]
    enabled = false
    title = "Lakshya Rastogi"
    subtitle = "Offensive Security Portfolio | CPTS Candidate"
    imageUrl = "https://github.com/LakshyaRastogi25.png"
    imageTitle = "My Avatar"
    imageWidth = 120
    imageHeight = 120

    [params.homeInfoParams]
    Title = "whoami"
    Content = "![Lakshya Rastogi](https://github.com/LakshyaRastogi25.png?size=120)
    Welcome to my digital workspace. I'm a computer science student specializing in offensive security and penetration testing.
    
    Here, I document my methodologies, from dissecting Web LLM vulnerabilities to writing commercial-grade engagement reports.
    
    If you're new here, feel free to check out my [About Me](/about/) page or browse my latest [CPTS Journey](/posts/my-cpts-journey/) updates."
    [[params.socialIcons]]
      name = "github"
      url = "https://github.com/LakshyaRastogi25"

    [[params.socialIcons]]
      name = "linkedin"
      url = "https://linkedin.com/in/lakshya-rastogi-0446a527b/"

    [[params.socialIcons]]
      name = "hackthebox"
      url = "https://app.hackthebox.com/users/1978596"

# --- Main Menu Configuration ---

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 10

[[menu.main]]
    identifier = "cpts-journey"
    name = "My CPTS Journey"
    url = "/posts/my-cpts-journey"
    weight = 40

[[menu.main]]
  identifier = "posts"
  name = "Blog"
  url = "/posts/"
  weight = 20

[[menu.main]]
  identifier = "reports"
  name = "Engagement Reports"
  url = "/reports/"
  weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true